language: csharp

os: linux # Ubuntu 14.04
dist: trusty
sudo: required
dotnet: 2.0.0

services:
  - docker

script:
  - dotnet restore
  - dotnet build src/LclDckr
  - dotnet test test/LclDckr.IntegrationTests
  
deploy:
  provider: script
  script: 
    - dotnet pack src/LclDckr --configuration Release /p:Version=$TRAVIS_TAG
    - nuget push src/LclDckr/bin/Release/*.nupkg -ApiKey $API_KEY
  on:
    tags: true
